### ISSUE TITLE
Embedable Developer Guide Content For NRU and other websites: March 31st

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1134]
### User Story

As a content create for [New Relic University](https://learn.newrelic.com/) it be cool to be able to take an existing guide, and easily embed that content into NRU. This would be a  stripped-down version of the page (without nav, header, footer, etc) for loading in an iframe .

The idea would a content creator could then leverage any guide that was created on the developer site or content on the dos or oss sites and easily embed that content and guide styles into NRU. Also it would be cool if this content could easily be emebbed in other websites that may want to use our guides.

Product Name: `Portable Developer Guides` 🤔 

### Example content cases

I want to embed the guide for [Build a Hello World App](https://developer.newrelic.com/build-apps/build-hello-world-app) into a learning course I've created on NRU. 

I want to embed the content on this docs page for [visualizations](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/add-custom-visualizations-your-dashboards)

### Considerations

- NRU is run on top of [Skilljar](https://www.skilljar.com/)
- Skilljar has an [API that could be useful](https://api.skilljar.com/docs/#) 🤷 
- Getting content into Skilljar may be tricky, the process we setup should require little to no engineering so a content creator can just grab a guide and embed , or import it into skilljar.
- ideally when a content creator does this, they are able to port over the content of the guide as well as the CSS styles and components of the guide. 
- Alternatively we could considering using iframes (it seems to be supported on Skilljar) or perhaps an interactive export of a guide (similar to how we embed [instruct content into our kubernetes guide](https://developer.newrelic.com/automate-workflows/get-started-kubernetes)

### Acceptance Criteria

- [ ] Ideally this functionality should be available for all sites: (OSS, Docs, Dev) If we had to pick one, starting with the Dev site content is preferred.
- [ ] Expose the stripped down page content via some URL or "endpoint"
- [ ] Each page has an "embedded" HTML version
- [ ] Embedded versions do not have global navigation, global footer, side nav, or in-page nav
- [ ] Theme of each page is set to the light theme
- [ ] Have this work completed by March 30th so @jaesius has time to do his side of this work.

~~_Note: this would be advantageous to complete (and document) by the end of February._~~

**Comment by jaesius** [comment]
After various meetings with the NRU team, it was decided that uses iframes would be the viable path. I'd still love to explore options using the API but haven't seen/heard anything that says it would be useful for our use case. 

Right now the goal is to embed a dev site guide into the LMS using an iframe but to pass a URL parameter that will remove unwanted UI components (IE. Sidenav) and possibly only returning light mode CSS styling.

**Comment by jpvajda** [comment]
Would also be cool to get tracking metrics on these so we can measure the interactions on these `portable` guides and what the source was for where the interaction occurred.

**Comment by zstix** [comment]
Technically speaking, I think we would like to add support for two optional URL parameters:
* `embed=true` to display a simplified UI without the Global Header, left-side nav, right-rail, and footer
* `theme=light` (or `dark`) to manually set the theme

I see this as a really great step towards making it easy to embed / share our docs in a variety of ways (in addition the NerdGraph, JSON, and RSS).

**Comment by jerelmiller** [comment]
For the simplified layout, I'd actually advocate for a `/embed` route of some kind for a few technical reasons.

We are generating the site ahead of time, which means we can't possibly know query params until the site is executed client-side. Because that code needs to execute client-side, you need to take 1 of 2 approaches to resolve this issue:

**Problems with query params**

1) Don't render the site until the query params are known

This is an approach we take on the attribute dictionary page. What you'll noticed when you load that page is that the data for that page is missing for a few seconds. This is because we download the raw HTML for the page, generated from Gatsby, but we block in JS until we can detect what query params are known. By blocking, this prevents a flash of all content, before we filter it down to the filtered event/attribute.

When talking about this approach for an entire site, this presents a problem as we'd need to block rendering of the site until query params are known and can be detected via JavaScript. This defeats the whole point of SSG (static site generation). Which leads us to option 2

2) Render the site, but adjust the layout when the query params are known and can be detected by JavaScript

Just to clarify, when I say "detected by JavaScript", I mean that our JavaScript is downloaded by the browser, parsed, and is able to execute. If we go this approach, this solves the problem from 1) by allowing the site to load and render as normal, but introduces a different problem: the dreaded FOUC (flash of unstyled content). _Technically_ it is styled, but in this case "unstyled" means "wrong layout". This means if we embed the page in a site, you'll see a flash with the primary layout before the layout is resolved and stripped down to the bare content.

This is undesirable from a UX perspective as this could be quite jarring.

**My proposal**

I propose that we instead create `/embed` routes for each page. Because this would be part of the path, this would allow us to generate the HTML for each page via SSG with the stripped down layout already in place. We don't need to do anything special client-side in order to render the stripped down layout.

Hopefully this helps!

**Comment by polfliet** [comment]
@jpvajda Beginning of April the beta testing for the developer certification is starting. We have this work in our current sprint, but just want to make sure we give this the right priority to get it done by March 31st.

**Comment by zstix** [comment]
## Acceptance Criteria
* [ ] Each page has an "embedded" HTML version
* [ ] Embedded versions do not have global navigation, global footer, side nav, or in-page nav
* [ ] Theme is set to the light theme

**Comment by jpvajda** [comment]
I've reached out to @jaesius to get a sense of when he'd need this done so he can do his part of the work on NRU with setting up the iframes
