### ISSUE TITLE
Public Catalog Nit Nit list `#2`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1405]
This is a collection of nits to fix in the public catalog. This list 2 of our nits. :D 

### Nits

- [x] Fix the lightmode fade on the dashboard image file as it's a not a subtle fade.  See PR  #1395
- [x] The last dashboard image in a gallery should have no fade See  See PR  #1395
- [X] Change dependencies to requirements  See PR #1419
- [x] ~~The nav item for `Observability packs` should be highlighted when on a pack details page~~ - `won't do` see comment

### Need new tickets and design input from @danielgolden 

- [x] ~~add a back button on the olly pack details page so a user can get back to the grid view~~
- [x] change the display of dashboard images as they are really small in the gallery view @roadlittledawn has an idea for this and will make a #PR
- [x] Confirm if the Gallery component still works for how we display dashboard images, as if they are small they don't really offer much value
- [x] The fading image approach doesn't seem to work now that we implemented can we take that out?
- [x] Default (varies by browser) `select` styling for tab items for mobile (screenshot is iOS firefox) is a little weird (see [screenshot in comment](https://github.com/newrelic/developer-website/issues/1405#issuecomment-863581489)) https://github.com/newrelic/developer-website/issues/1421

**Comment by roadlittledawn** [comment]
o11y pack detail page screenshot (iPhone X Firefox)
![IMG_8D7008DEA995-1](https://user-images.githubusercontent.com/2952843/122475482-93a52c00-cf79-11eb-86cf-97024189cc44.jpeg)

**Comment by zstix** [comment]
> The nav item for Observability packs should be highlighted when on a pack details page

This would require a (somewhat significant) change to the way that the theme renders "active" navigation links. At the moment, the navigation item that's highlighted is the _current_ page. If we wanted, we could add the packs as their own navigation items in the nav, but I don't think that would scale well.

I think we should leave this _as is_. If we changed it as suggested, we would run the risk of the user thinking that they're _on_ the observability pack page and they might not realize that they can click on that link to get back.

**Comment by jpvajda** [comment]
We are reviewing the UI feedback under the Needs New ticket section above with @danielgolden this week, once we have confirmation how to proceed I can make the necessary tickets for implementation. Moving to Sprint 7 as this ticket will carry over.
