### ISSUE TITLE
Provide banner element and new IO logo

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1414]
1. Provide a new I/O Logo
2. provide I/O banner and layout

### Acceptance Criteria

- [X] work with `Moe Hung`
- [x] new IO Logo  SVG Format  See this [JS file](https://github.com/newrelic/developer-website/blob/develop/src/%40newrelic/gatsby-theme-newrelic/components/Logo.js) for how it's done on the developer site.
- [x] banner design and layout
- [x] ~~Obtain design element for the overview page~~ [ no longer needed]
- [x] ~~Obtain design element for alerts~~ [ no longer needed]
- [x] ~~Obtain design element for synthetics~~ [ no longer needed]
- [x] ~~Obtain a design element for dashboards~~ [ no longer needed]
- [x] ~~Obtain a design element for visualizations~~ [ no longer needed]

**Comment by kukukaka** [comment]
@jpvajda we are talking about placeholders for each one of them, right?

**Comment by jpvajda** [comment]
@kukukaka correct. it's a placeholder image we'd use that has some style /brand our new relic elements that would communicate what these things are in a visual way...

It may not something you do, but there is a need for it, and I'm not sure what design team does this work for New Relic, so we just have  ticket for it to ensure it eventually gets done. So if you can give us direction on this we can consider what to do in these cases.

**Comment by jpvajda** [comment]
@polfliet is going to share with the marketing team for resourcing.

**Comment by jpvajda** [comment]
@DustinFinkle Thanks, let me know if we can provide any clarity for this request.

**Comment by jpvajda** [comment]
This work is being handle in #1570 so closing as this was just a tracking ticket
