### ISSUE TITLE
[Public Catalog] Provide a featured filter for packs that are tagged as featured partner packs

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1420]
Provide a featured filter for packs that are tagged as featured partner packs. This is dependent on the partner work Buddy is doing. If we decide to feature packs, we'd want a way for a user to quickly be able to filter these in the public catalog.

### Acceptance Criteria

**UI**

- [x] A category filter is available called `Featured`
- [x] This filter would showcase the olly packs that contain the featured label as a keyword. 
- [x] the filter value should be available as query param in the URL ```https://observabilitypacks.gatsbyjs.io/observability-packs/?filter=Anything&sort=Featured```
- [x] organize packs by featured first in alpha order, then all the rest of the tiles in alpha order in the catalog (marketplace) section. 
- [x] Packs that  are featured would have a label `featured` visible  Relates to #1561

**Comment by jpvajda** [comment]
@polfliet discussed this need with @kidk and he was OK with DevEn contributing this feature to the olly pack configuration.

**Comment by kidk** [comment]
Let us know how this comes out, and if/when we need to add it to the API.

**Comment by jpvajda** [comment]
several questions on this before we can implement.

**Comment by zstix** [comment]
A couple of questions on the implementation of this:
* What field this will be in the API (is this a `featured` boolean? is it part of a `tags` list?)
* How will this be presented in the UI?
* How will this interact with the search, sort, and filtering?
* How do we want to update what is featured?

**Comment by jbeveland27** [comment]
I think these are all good questions raised by @zstix. On this one specifically:

> What field this will be in the API (is this a `featured` boolean? is it part of a `tags` list?)
I think `tags` could work for this use case and it wouldn't require adding anything additional to the config-spec. 

It also makes me wonder: are we planning to do the same type of filtering for the in-product UI or is this only for the developer site?

[VIRTUOSO-1122](https://newrelic.atlassian.net/browse/VIRTUOSO-1122) is the ticket for us to add this to the service.

**Comment by jpvajda** [comment]
@jbeveland27 feature packs would also be in the product ideally.

**Comment by jpvajda** [comment]
featured functionality would be available in nerdgraph eventually that can we can read from.... to show the feature packs as a filter.

**Comment by jpvajda** [comment]
updated

**Comment by rudouglas** [comment]
Here are the designs I have done for this so far, the last thing to implement is the actual query param filtering:
<img width="1406" alt="Screenshot 2021-09-10 at 15 53 28" src="https://user-images.githubusercontent.com/17122543/132878167-5a22ca80-b19a-4cad-b9d2-56c6d1a445ce.png">
<img width="1390" alt="Screenshot 2021-09-10 at 16 15 37" src="https://user-images.githubusercontent.com/17122543/132878175-322e1986-71c7-4f6c-871b-f8ea9f2dfe16.png">

**Comment by aswanson-nr** [comment]
@jpvajda The filter and label have been added, the only thing left is adding the `featured` keyword to the specified quickstarts. Have you heard anything from Buddy?

**Comment by jpvajda** [comment]
@aswanson-nr they'll be added where applicable to those packs we need to feature, Jemiah was running point but let me ask @polfliet if we have a list

**Comment by polfliet** [comment]
I can make a PR once we have all of the partner quickstarts in, but we don't have them yet.
Normally it will be Kentik, Lacework, Trend Micro, Fastly, Cribl

**Comment by jpvajda** [comment]
@polfliet awesome, here is a 🎫  https://github.com/newrelic/newrelic-observability-packs/issues/244

**Comment by aswanson-nr** [comment]
@jpvajda Since we have newrelic/newrelic-observability-packs#244, can we close this ticket out?

**Comment by jpvajda** [comment]
Yes sir.
