### ISSUE TITLE
[Public Catalog] Use the new summary field to populate the pack catalog view

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1467]
Once we have the new field for summary we can use that content to populate the catalog view of all packs instead of using a truncated version of a description.

### References

- [summary field limits ](https://github.com/newrelic/newrelic-observability-packs/blob/main/CONTRIBUTING.md#summary)
- [Pack Config File Schema](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/config-spec.md)
- [Pack Config Template](https://github.com/newrelic/newrelic-observability-packs/blob/main/_template/config.yml)

### Acceptance Criteria

- [x] Confirm with @jbeveland27 when the summary field will be added to the Schema (_WIP_)
- [x] Confirm with @jbeveland27 the summary field will be required in the schema
- [x] confirm with @austin-schaefer who can assist us from the Docs Team
- [x] Updated a pack with a summary of the description with help from our Docs Team friends.
- [x] use these summaries to populate the catalog view of olly packs for both full packs and integration pack types.
- [x] A pack summary in the grid /list view will be plain text only
- [x] When complete @jpvajda will notify DevEx how they can also use this summary field in the same way in the product catalog.

<img width="1389" alt="Screen Shot 2021-07-23 at 12 46 26 PM" src="https://user-images.githubusercontent.com/1395158/126827879-f8bd773b-bee3-496a-9158-9ee1b3168463.png">

**Comment by jbeveland27** [comment]
I added [VIRTUOSO-1122](https://newrelic.atlassian.net/browse/VIRTUOSO-1122) to track the schema updates. 

Note: The summary field can be added to packs before we update the service, it just won't be present until the service is updated (i.e. the order of work doesn't have to be dependent on the service getting updated first)

**Comment by rudouglas** [comment]
@jpvajda I have the code complete for this, and all the `integration` packs have summaries, just the original ones need summaries now, who from the Docs team is assisting on this so I can follow-up? @austin-schaefer

**Comment by jpvajda** [comment]
@jpvajda those summaries are being written in collaboration with our SEO partner. I'll add you to our slack room with them.

**Comment by rudouglas** [comment]
thank you sir

**Comment by jpvajda** [comment]
@bradleycamacho is helping to update the QSs with the summary fields as those are being defined.
