### ISSUE TITLE
[Publc Catalog] Implement pack ID cookie approach

### ISSUE THREAD

**Issue by LizBaker** [newrelic/developer-website#1518]
In https://github.com/newrelic/newrelic-observability-packs/issues/127 we added a test cookie to the dev site under the new relic domain to see if a cookie could be a viable option for virtuoso to persist a pack ID when a user has to first sign up for new relic after clicking "install" on a quickstart

once we have confirmation about their ability to read the test cookie we can add a cookie with the pack ID to the feature branch on the dev site

AC:
- [x] Follow up with @mbazhlekova and @jbeveland27  about the cookie plan 
- [x] obtain input from the virtuoso team on this approach. `VIRTUOSO-1262`
- [x] Implement the cookie approach.

**Comment by jpvajda** [comment]
We can do this work in our site epic for building the new site but I would be good to confirm this approach prior as that epic is a few weeks away for us, so I'll ask @kidk if he could prioritize this confirmation sooner than later @LizBaker

**Comment by jpvajda** [comment]
from @mbazhlekova  

> I started looking at this but got sidetracked. Sam and I will be on FTO for the rest of the week but I'll tag @jeveland and @mro here to potentially look into this. I'm not totally clear on whether the API or the nerdlet should read the cookie.

**Comment by jpvajda** [comment]
following up on how we can confirm our approach with @jbeveland27

**Comment by jpvajda** [comment]
This is currently in priority by Virtuoso to start this development soon.

**Comment by jpvajda** [comment]
This is now unblocked as VIRTUOSO-1262 is done
