### ISSUE TITLE
[Public Catalog] Use different layout for quickstart landing page

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1534]
## Summary

In order for quickstarts to look more like a standalone site, we want to change the layout so:
* left sidebar contains quickstart filters for pack contents & eventually keywords
* remove sort for now
* search input for name/description is always expanded at top of main column (grid/list view buttons stay to right of it)

## Remaining work in branch

I did [some initial work](https://github.com/newrelic/developer-website/tree/clang/quick-start-layout) to use different layout, incorporate the back button PR, and updated the form controls.

Remaining work includes:
* finish mobile / responsive layout on smaller screens (make form controls as compact as possible) 
* automatically search via debounce
* possibly refactor, split some code out to make it more readable, reduce size of file

### Mocks
![2021-08-27_14-08-00](https://user-images.githubusercontent.com/2952843/131188765-f4478c4b-c309-4fb9-8c0f-32cebda73e7f.png)

## Acceptance criteria
- [x] When you search, you can go forward / backward in browser history for each search
- [x] On landing page, left sidebar only has quick start items/content (including pack contents filter)
- [x] When you search, filters are applied automatically
- [x] Filters are applied individually there is no multi-select filter exp at this time. 
- [x] Debounced search doesn't make the page load too many times, look jumpy / stalled, etc.
- [x] Page is responsive: single stacked column with all form controls at top (similar to current behavior)

## Helpful links
https://github.com/newrelic/developer-website/issues/1536
https://github.com/newrelic/developer-website/issues/1559
[quick-start-layout branch](https://github.com/newrelic/developer-website/tree/clang/quick-start-layout)

**Comment by jpvajda** [comment]
Updated AC about how filters aren't multi-select.

**Comment by jpvajda** [comment]
related improvement: https://github.com/newrelic/developer-website/issues/1575
