### ISSUE TITLE
[Instrumentation] Ensure key interactions / analytics are tracked via Tessen

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1538]
## Summary

We want to ensure all key interactions / analytics are being instrumented and reported as expected via Tessen. We also want to update naming convention for data we're sending from `observability pack` to `quick starts`  (and variations thereof).

We can remove the `PageAction` calls in favor of Tessen equivalents, unless there's good reason to track with both.

## Events to capture
i/o page
- [x] landing on instant observability page (filter state, view state)
- [x] view - list, grid
- [x] filter - all, dashboards, alerts, data sources, etc
- [x] search
- [x] selecting a quickstart
- [x] selecting build your own quickstart

quickstart details
- [x] view repo button
- [x] installation button (or view documentation)
- [x] tab selection (overview, dashboard, alerts, data sources, etc)

## Acceptance criteria
- [x] For all existing `PageAction` events, we send relevant Tessen calls
- [x] Verify data is reporting as expected (via Segment debugger OR NR1 `TessenAction`)

**Comment by nr-kkenney** [comment]
everything listed above is currently tracked with the merge of #1595. closing as done.
