### ISSUE TITLE
[Public Catalog] Install Button and View button Improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1553]
We've gotten feedback from several people including that the install button on the external I/O site feels out of place. How about we move it down in the "right rail" and add the [feather icon ](https://feathericons.com/)for a `+` to it, so it matches the Github Button. (_we use the feather icon library on the developer site_) 

 the install button should be the darker color and the Repo button transparent (similar to what you see in the [right rail on this page](https://developer.newrelic.com/automate-workflows/5-mins-tag-resources/).) As install is the primary action. 

### crude mockup below :artist:

<img width="507" alt="Screen Shot 2021-08-26 at 5 24 00 PM" src="https://user-images.githubusercontent.com/1395158/131155849-a21aaeda-5b18-47ac-8181-b4e28aa4fd28.png">

### Acceptance Criteria

- [x] move install button to right rail
- [x] add `+` feather icon 
- [x] set view repo button to transparent with border

**Comment by rudouglas** [comment]
![](https://user-images.githubusercontent.com/17122543/131517679-1a637505-c227-481f-8e21-56f80fd29b66.png)

**Comment by jpvajda** [comment]
We need the + icon, it's in the AC so let's add that in the so the buttons both have icons. @rudouglas

**Comment by rudouglas** [comment]
@jpvajda how does this look

<img width="1472" alt="Screenshot 2021-08-31 at 16 33 26" src="https://user-images.githubusercontent.com/17122543/131533067-81c4cfbd-b12f-4d6b-a47f-2540375e0100.png">
<img width="655" alt="Screenshot 2021-08-31 at 16 33 34" src="https://user-images.githubusercontent.com/17122543/131533073-f3f09e6b-4df1-485d-a630-252884aa142f.png">
<img width="352" alt="Screenshot 2021-08-31 at 16 34 19" src="https://user-images.githubusercontent.com/17122543/131533076-4d9ef4ef-3b39-4a4f-ba4c-2623cbd47880.png">

**Comment by rudouglas** [comment]
PR for adding plus icon to theme https://github.com/newrelic/gatsby-theme-newrelic/pull/445

**Comment by rudouglas** [comment]
@jpvajda I opted to not show the `+` when on a docs only pack, as I didn't think it make sense to include it, what do you think?
<img width="465" alt="Screenshot 2021-09-03 at 15 20 48" src="https://user-images.githubusercontent.com/17122543/132021066-76336870-fc70-4c2f-bcb4-0c9ce1ad1c2c.png">

**Comment by jpvajda** [comment]
@rudouglas oh yeah good call! I love it.
