### ISSUE TITLE
[Public Catalog] Add the tile overview to the external catalog pack overview section

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1555]
The in product catalog has this new treatment  that provides a visual of what is in a pack, we should also do this in the external catalog 

### Mock Up 
<img width="1202" alt="Screen Shot 2021-08-26 at 5 54 56 PM" src="https://user-images.githubusercontent.com/1395158/131167152-2494c644-0e15-4609-91c0-99f9e2a26ae6.png">

### Acceptance Criteria 

- [x] Represent which components are in a pack on the overview page using summary tiles.
- [x] Follow the in product design for guidance. 
- [x] Overview includes all pack contents (alerts, dashboards, data sources)
- [x] Show Details of Alerts as specified in the yml limited to ideally: Truncate by number of lines (2) OR  if not possible 250 characters in the overview 
- [x] Show a primary dashboard image, if a dashboard exists.

**Comment by jpvajda** [comment]
Clarified some AC after speaking to Daniel.

**Comment by jpvajda** [comment]
@nr-kkenney further clarifications on truncation of text let me know if we should discuss.
