### ISSUE TITLE
[Public Catalog] Use different layout for quickstart details pages

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1559]
## Summary

We want to change the layout of a quick start details page so:
* there is no left sidebar, and content takes up full width of page
* include breadcrumbs at top (similar to NR1 catalog details page)
* exclude mobile nav hamburger menu

Consider creating `Breadcrumbs` component in the theme for docs site to use in the future.

## Remaining work in branch

Some of the work here is already in [this branch](https://github.com/newrelic/developer-website/tree/clang/quick-start-layout). Remaining work includes:
* include breadcrumbs at top (similar to NR1 catalog details page)

### Mock

![2021-08-27_13-58-24](https://user-images.githubusercontent.com/2952843/131188044-d1abe1c8-8827-405b-abad-f641d69c47f6.png)

**breadcrumbs in NR1**
![2021-08-30_11-48-36](https://user-images.githubusercontent.com/2952843/131389407-a32cbdc8-4fe6-4794-884f-0ee14ec1c174.png)

## Acceptance criteria
- [x] Each quick start page is full page width (like mock), no sidebar
- [x] If I view details page on mobile, there's no hamburger menu / nav and page is responsive
- [x] As a user, I can get a sense of where I am by viewing breadcrumbs, and clicking on link to quick starts landing

## Related links
https://github.com/newrelic/developer-website/issues/1534
https://github.com/newrelic/developer-website/tree/clang/quick-start-layout

**Comment by nr-kkenney** [comment]
closing since all prs merged, criteria checked off.
