### ISSUE TITLE
[Public Catalog] add labels to packs in the grid view

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1561]
The in-product has the concept of labels applied to the grid view so each tile can reflect the type of tile it is, Ex: Quickstarts, Nerdpacks, Visualizations, etc. We'll want to do something similar in the external site.  We'll only be starting with the featured label, since we only show quickstarts on the external site, but we'll lay the foundations for labeling in this ticket.

Relates to #1420

### General Label Logic 

`to confirm`: We will not use the label: data source  & just call them quickstart  Internally, since nerdpacks are also in the catalog, the quickstart label will be used. externally we don't have nerdpacks in the catalog, so we won't use the label quickstart for now.  Both internal an external catalogs will use  the featured label

### Acceptance Criteria 

- [x] A quick start has a label called `Featured`
- [x] the label is visible in both grid view and list view
- [x] The label color can follow our pattern of color on our sites.

### Mock Up 

**In Product**

<img width="1109" alt="Screen Shot 2021-09-03 at 4 54 59 PM" src="https://user-images.githubusercontent.com/1395158/132072419-7956324c-418b-4169-9dda-e4f0b95a688f.png">

**Comment by jpvajda** [comment]
updated with the focus on featured QSs only

**Comment by rudouglas** [comment]
<img width="1406" alt="Screenshot 2021-09-10 at 15 53 28" src="https://user-images.githubusercontent.com/17122543/132877962-a09e25ed-3fce-4556-b60c-de5e0716dc9a.png">
<img width="1390" alt="Screenshot 2021-09-10 at 16 15 37" src="https://user-images.githubusercontent.com/17122543/132877975-1d1e553c-5fc4-4c15-b1e7-03741bad3625.png">
