### ISSUE TITLE
[Public Catalog] Select a category and  select a component filter which will filter Quickstarts in the selected category.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1575]
The long term intention for the interaction between filters and categories is that a user can select a category and then select a keywod filter which will filter items in the selected category. 

- Dependency on keywords being added to the repo -> `Cloud enablers`
- The initial approach will use a hard coded list stored in the repo

### Acceptance Criteria

- [x] Use the list in `G-Drive New Relic I/O` - `Keywords & Categories`  to map categories to keywords. 
- [x] A user can select a` single` category filter (infrastructure, AWS, etc)  and the quickstart tiles filter accordingly
- [ ] A user can deselect the category filter to remove it. (In product is using a little `x` button)
- [x] A user can then select `single` component filter (alerts, dashboard, etc)  and the quick starts tiles in the that category filter accordingly. 
- [x]  Can we add a filter called `data source`? it sounds like the internal catalog will have a filter to do this that would filter the QSs by those with `data sources`
- [x] The URL will reflect the selected category and filter params.
- [x] Text searches should compare against keywords 
- [x] Mobile layout should use selects for categories
- [x] Mobile categories should be clearable
- [x]  all Categories should be in sentence case:  `Browser & mobile`, NOT `Browser & Mobile`
- [x] Categories WILL  have counts returned like component filters.

### mock up 🎨 

<img width="280" alt="Screen Shot 2021-09-10 at 2 44 37 PM" src="https://user-images.githubusercontent.com/1395158/132916609-102d9c1b-7856-47d0-9c16-d6b91dcccc18.png">

**Comment by jpvajda** [comment]
add the category approved list to define the categories...

**Comment by jpvajda** [comment]
The internal category list is here > `G-Drive` `New Relic I/O - Keywords & Categories`

**Comment by jpvajda** [comment]
I got some good details on this approach and referenced the ticket where DevEx is adding a new field to the schema and API for category. cc @aswanson-nr

**Comment by jpvajda** [comment]
I confirmed with @danielgolden and @JuliaNocera how this will work for GA, add the details in the ticket.

**Comment by jpvajda** [comment]
We have several questions that the epic captain will reach out to DevEx to confirm.

**Comment by jpvajda** [comment]
updated after our chat with dev ex

**Comment by jpvajda** [comment]
cofirmed with A-Watts Categories should have counts.
