### ISSUE TITLE
Final instrumentation checks

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1603]
## Description
Most of the instrumentation has been completed as we worked through the project, this is just to catch anything we missed and verify that events are properly being propagated through the system.

### Acceptance criteria
- [ ] The [Wiki documentation](https://github.com/newrelic/developer-website/wiki/Editing-Event-Data-and-Instrumentation) is updated to include any new events from I/O.
- [ ] Ensure that pack installs can be tied to new user signups, work with Zoe to confirm this.
- [ ] Fill in any missing events (NOTE: we might want to time box this ticket because of this AC)

**Comment by jpvajda** [comment]
I've gone ahead and updated the WIKI for event types https://github.com/newrelic/developer-website/wiki/Editing-Event-Data-and-Instrumentation#event-data-1

**Comment by aswanson-nr** [comment]
Previous event work https://github.com/newrelic/developer-website/issues/1538

**Comment by jpvajda** [comment]
@jpvajda will work with @roadlittledawn on what existing events there are and then I can define if we need to consider instrumenting anything else.  We can also confirm the naming convention we are use for event names.

**Comment by jpvajda** [comment]
Starting this work now..

**Comment by jpvajda** [comment]
I've followed up with Zoe in Slack to see if we can confirm that quickstart installs can be tied to new user signups.
