### ISSUE TITLE
[Public Catalog] Add crazyegg tracking to script to I/O

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1818]
Jason Chen is asking to add CrazyEgg to analyze the click patterns as It will help us in seeing where customers are clicking and will give us a heatmap.

`<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0045/9836.js" async="async" ></script>`

### Question

- [x] We want it just on the main grid view? Why not product details?  would be cool to see heatmap click data for details pages IMHO if it's not to performance impacting

> No. we have a hard cap of i think 200 active pages we can track in total, and with ~400 quickstart pages we'd exceed that.

### Acceptance Criteria

- [x] Do a performance test after deploy to understand impact and provide data on impact.
- [x] Add script to this page https://developer.newrelic.com/instant-observability/
- [x ] When done, confirm with `JasonChen`  -- @jpvajda 
- [x] confirm if this is temporary or permanent with `JasonChen` -- @jpvajda

**Comment by jpvajda** [comment]
Lighthouse score as of 11/3/21

<img width="1876" alt="Screen Shot 2021-11-03 at 5 19 35 PM" src="https://user-images.githubusercontent.com/1395158/140232056-1cd9046e-1a79-4655-955b-6a4dc116fada.png">
