### ISSUE TITLE
[Dev Site] Add crazyegg tracking to script to Devsite home

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1845]
Relates to #1818 

Jason Chen is asking to add CrazyEgg to analyze the click patterns as It will help us in seeing where customers are clicking and will give us a heatmap.

`<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0045/9836.js" async="async" ></script>`

### Acceptance Criteria

- [ ] Do a performance test after deploy to understand impact and provide data on impact.
- [x] Add script to this page https://developer.newrelic.com
- [ ] When done, confirm with `JasonChen`  -- @jpvajda 
- [x] confirm if this is temporary or permanent with `JasonChen` -- @jpvajda

**Comment by jpvajda** [comment]
I have a PR for this change, but I don't think Gatsby like the use of the tienary operator as I'm seeing an error, though the site builds and the script seems to fire ok on each page I've set it on.


<img width="1176" alt="Screen Shot 2021-11-08 at 4 04 10 PM" src="https://user-images.githubusercontent.com/1395158/140832236-d9627f6d-a819-44a0-8126-5bf6d16439c0.png">

**Comment by jpvajda** [comment]
Used an `||` statement instead, seemed to work... 🤷

**Comment by jpvajda** [comment]
This approach also seems to throw the same errors

```
Uncaught Error: CE: multiple userscripts installed
    <anonymous> http://script.crazyegg.com/pages/scripts/0045/9836.js:1
9836.js:1:70
    <anonymous> http://script.crazyegg.com/pages/scripts/0045/9836.js:1
```
