### ISSUE TITLE
[Public Catalog] Update search, sort, and filtering to use SSR

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1855]
## Description
Once we have established a pattern for querying NerdGraph for quickstarts on the landing page (#1853), we should use the API to power the functionality for searching, sorting, and filtering the results. This would _replace_ our client-side functionality (which has gotten to be pretty complicated).

## Acceptance Criteria
* [ ] https://github.com/newrelic/developer-website/issues/1821 (proof-of-concept & Gatsby upgrade)
* [ ] https://github.com/newrelic/developer-website/issues/1852 (feature branch & Gatsby Cloud)
* [ ] https://github.com/newrelic/developer-website/issues/1853 (landing page via SSR)
* [ ] Update search to use use SSR + a NerdGraph API call
* [ ] Update sorting to use SSR + a NerdGraph API call
* [ ] Update filtering to use SSR + a NerdGraph API call
* [ ] Ensure that searching, sorting, and filtering still updates the URL as it did previously
* [ ] Remove all unused client-side search, sort, and filter code

**Comment by zstix** [comment]
You can explore our GraphQL API here: https://staging-api.newrelic.com/graphiql

**Comment by jpvajda** [comment]
blocked by Gatsby Cloud having private variable functionality. ETA end of Jan.
