### ISSUE TITLE
[Public Catalog] Instrument & Alerting for API calls to NerdGraph

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1857]
## Description
As part of "production readiness" for swapping New Relic I/O over to being powered by NerdGraph, we should instrument the API calls being made and set up some alerting for failures.

It's not clear in which context the API calls are being made: are they happening in the browser or are Gatsby's Cloud Functions executing "server-side" somewhere? If they're happening client-side, we may be able to use New Relic's Browser agent to log these events. If they're happening server-side, then we may need to leverage [New Relic custom events](https://github.com/newrelic/developer-website/issues/1855) (since we don't have an agent installed in Gatsby).

## Acceptance Criteria
* [ ] https://github.com/newrelic/developer-website/issues/1821 (proof-of-concept & Gatsby upgrade)
* [ ] https://github.com/newrelic/developer-website/issues/1852 (feature branch & Gatsby Cloud)
* [ ] https://github.com/newrelic/developer-website/issues/1853 (landing page via SSR)
* [ ] https://github.com/newrelic/developer-website/issues/1855 (search, sort, filter via SSR)
* [ ] https://github.com/newrelic/developer-website/issues/1854 (details page via SSR)
* [ ] Determine how we can get API call information into New Relic
* [ ] Set up instrumentation for API calls to NerdGraph
* [ ] Set up an alert condition for "High number of failed API calls"

**Comment by zstix** [comment]
I've got a PR up for the code to send custom events to New Relic (linked). Once this is set up and verified, I'll look into creating the alert condition and updating our dashboards.

**Comment by jpvajda** [comment]
blocked by this lack of functionality of Gatsby Cloud not supporting private environment variables.
