### ISSUE TITLE
update developer site with missing content from Dev Site migration from AEM

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#959]
When migrating content to the new developer site decisions were made to not migrate some data and also to move some content into other areas of the site with the new IA. In doing that some context was lost for critical documents customers need. So this task is to ensure we bring over all the missing content and ensure it has a proper home on the new Dev Site.

### Tools to get started on this task

1. You'll need access to [AEM -Adobe Exp. Manager](https://author-newrelic-prod2.adobemsbasic.com/sites.html/content/newrelic/developer/build-tools/new-relic-one-applications) Where the old site content resides. 
2. You'll want to review this [migration inventory](https://docs.google.com/spreadsheets/d/19_jSzyFlylMffYHalU4Jq7-JhO-z2iZOKBQGJnClfJI/edit#gid=2094893399) and look at the Post Migration Task column and AEM reference column for instructions.
3. As needed make the necessary corrections on the new developer site, but ensure if you have questions or doubts on adding content that you discuss that with @mmfred and @jpvajda 

## @TODOS

- [x] add how to extend webpack configuration to the Build a hello world App guide.

`
You can use our .extended-webpackrc.js file to extend the webpack 4 configuration. This allows you to add your own aliases, scripts, and configurations when locally serving or deploying your app.
`

- [x] add how to handle proxy browser setup to hello world App guide.

```
Generally, you don't need to know how your application code is loaded in New Relic One. But understanding how this works can help you if you encounter issues (for example, with a proxy or browser setup). 

When developing, your code is served from your local laptop by using an nr-local.net subdomain. This domain points to 127.0.0.1, and will use a variety of ports to connect, including 9973.

In order to load third-party code into the platform, (both in development and production), New Relic One uses an <IFRAME>, as well as a separate domain (a subdomain of nr-ext.net) to perform the load, relying on same-domain policy to sandbox the code.

For this reason, your network administrator may need to enable access to:

 Any subdomain of nr-local.net, or, at the very least, to any domain of the shape of <UserId>.nr-local.net, where UserId is a 32-hexadecimal character identifier that is unique to the user logged into the platform (you can use [0-9a-f]{32} to discriminate it).

Any subdomain of nr-ext.net, or, at the very least, to any domain in the shape of <NerdpackUuid>.g<NerdpackGid>.nr-ext.net, where NerdpackUuid is the UUID assigned to your package, and NerdpackGid is zero, or a positive integer (you can use 0|[1-9]\d+ to discriminate it).
```

- [x] write a guide on using charts based on the [Chart library page](https://author-newrelic-prod2.adobemsbasic.com/sites.html/content/newrelic/developer/build-tools/new-relic-one-applications/chart-library)  https://github.com/newrelic/developer-website/issues/975

- [x] add an API landing page that opens when a use clicks on Try our APis

- [x] Add link to the [Log API documentation](https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api) to the API nav section of the site.

- [x] Add link to the [Metrics API documentation](https://docs.newrelic.com/docs/telemetry-data-platform/get-data/apis/introduction-metric-api) to the API nav section of the site.

- [x] add a link to the [Trace API documentation](https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api/introduction-trace-api) to the API nav section of the site

- [x] add a link to the [Event API documentation](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/use-event-api-report-custom-events) to the API nav section of the site.

**Comment by jpvajda** [comment]
I'll be taking this one @mmfred.

**Comment by jpvajda** [comment]
I've asked @mmfred  to review my findings.

**Comment by mmfred** [comment]
This looks good @jpvajda - there's one topic that you flagged as needing a bit more coverage in docs. I'll follow up separately about making a docs ticket for that.

**Comment by jpvajda** [comment]
@mmfred thanks, which topic was that?

**Comment by mmfred** [comment]
Oh, it was /technology/infrastructure-sdk
And on rereading, you weren't asking for more coverage in docs.
